const MENU_NOTE = "Menu names differ by software version, car and region. Follow the on-screen prompts and the tool's vehicle coverage list. Where menu names are given they are indicative only, so trust what your tool actually shows.";
const LEGAL = "Only program keys for vehicles you own or have proof of ownership / written authority for. Note what proof you saw (e.g. ID plus ownership papers) and don't proceed if something feels off.";
const KEYPRE = [
 "Owner (or authorised person) present, with ID and proof of ownership or authority",
 "Vehicle make/model/year/immobiliser type confirmed on the tool's coverage list for the function you want",
 "Battery charger / stable power supply connected; lights, stereo and other loads off",
 "Tool charged, registered and updated; software current for that make",
 "New key / remote of the correct type, chip and frequency for the car (check before opening the car)",
 "All existing working keys on hand - some procedures erase old keys and you may need them present"
];
const KEYPROB = [
 "Tool won't talk to the car: re-seat the OBD connector, check ignition state, re-pair the interface, re-check the vehicle selection and year",
 "Key not detected / read fails: reposition the key in the slot, try another blank, check chip type and frequency",
 "Procedure stops with an error: note the exact message, check power, and don't loop the same step blindly - re-read the prompt first",
 "New key starts the car but the remote buttons don't work: the transponder and remote are separate steps - repeat the remote step",
 "Function not listed for your car: it's not supported on your tool/version. Don't force it - refer the job on or decline"
];
const KEYWARN = [
 LEGAL,
 "Keep power stable for the whole job. A drop mid-procedure can leave the immobiliser in a bad state.",
 "Some procedures erase previously learned keys. Read each prompt and test every key at the end.",
 "Never promise a result before you've checked coverage on the tool itself."
];
const TEST_END = "Test everything: start the car with each key, check remote lock/unlock, and lock the car then re-open it. Save or screenshot the job record if the tool offers it.";
const PREF = ["Laptop plugged in with sleep/hibernate off, antivirus/auto-updates paused", "Battery charger on the car and holding steady voltage", "Original ECU file saved and copied to a second location before any write", "Correct cable/adapter and drivers installed, and the car identified (ECU/ROM ID noted)"];

const GUIDES = [
// ---- KM100X
{tool:"Autel MaxiIM KM100X", title:"Add a spare key (IMMO)", pre:KEYPRE.concat(["VCI (MaxiVCI V200) paired with the tablet and plugged into the OBD port"]),
 steps:[
  "Check ownership / authority and coverage before you start.",
  "Connect the charger, then plug the VCI into the OBD port. In VCI Manager pair the VCI (shows as 'Maxi' plus a serial number). The connection LED goes solid blue when paired over Bluetooth.",
  "From the Job Menu open IMMO. Identify the car with AutoVIN or by selecting make, model and year manually. Confirm the details shown.",
  "Optionally run the IMMO status scan / read the immobiliser information first so you can see the key count and any faults.",
  "Look for the key learning / add key function. The manual shows it can appear under the status scan, Control Unit -> Immobilizer, or a Hot Function, depending on the car.",
  "Follow the prompts exactly: ignition on/off at the right moments, insert the right keys, wait for the progress messages.",
  TEST_END],
 prob:KEYPROB, warn:KEYWARN},
{tool:"Autel MaxiIM KM100X", title:"All keys lost (AKL) - supported cars only", pre:KEYPRE.concat(["Confirmed on the tool or Autel's support list that AKL is available for that exact car and year", "Be ready for extra steps such as reading ECU/immobiliser data or entering a PIN, depending on the car"]),
 steps:[
  "Verify ownership / authority first. AKL is the job where this matters most.",
  "Check AKL coverage for the exact car and year. AKL is only available on selected vehicles, not universally. If it isn't listed, stop here.",
  "Connect power, pair the VCI, and open IMMO. Identify the vehicle (AutoVIN or manual selection).",
  "Look for an all-keys-lost / key learning route under the manufacturer's menu. Where it sits varies with the car.",
  "Follow every prompt. Some cars need a PIN or immobiliser data obtained by the tool first - let the tool do that rather than improvising.",
  "Program the new key(s) as prompted. Make sure the blade is already cut and fits before you start (see the key cutting prep guide).",
  TEST_END],
 prob:KEYPROB.concat(["AKL path not offered: it's likely unsupported for that car on your tool/version - refer the job on rather than trying workarounds"]), warn:KEYWARN.concat(["Don't offer AKL as a service on a model until you've confirmed it on a real job record or the tool's coverage list."])},
{tool:"Autel MaxiIM KM100X", title:"Generate a universal key (IKEY)", pre:["Car and function confirmed on the coverage list", "Autel universal key (IKEY) with a good battery fitted", "Only one universal key near the key slot", "Owner consent / proof of ownership"],
 steps:[
  "Fit a fresh battery in the universal key.",
  "Open the Universal Key app. Choose the region, then enter the vehicle (manual input, AutoVIN, or scan licence plate / VIN if offered).",
  "Tap the key information shown for your car to read the detailed operation instructions.",
  "Place the universal key in the key slot and keep it still. Keep other universal keys at least about 10 cm away.",
  "Tap Generate Universal Key and wait for the completion message.",
  "Tap the IMMO button (or return to IMMO) to teach the new key to the car, then test it. If the buttons are wrong, look for Button Customization under Special Functions."],
 prob:["Generation fails: dead battery, key not seated, or RF interference are the common causes listed in the manual", "Warning to re-place the key: reseat it and hold it still"], warn:[LEGAL, "Generating the key doesn't program the car to accept it - the IMMO step does that."]},
{tool:"Autel MaxiIM KM100X", title:"Read and clone a transponder (Reading/Cloning)", pre:["Original working key available and owned by the customer", "Blank transponder of the right type", "Tool charged", "Owner consent"],
 steps:[
  "Open Reading/Cloning. Put the key in the key slot (or the bare transponder in the transponder slot) and tap Read.",
  "Note the chip type, immobiliser type, transponder ID, locked state and code mode shown. Re-seat and retry if the read fails.",
  "If the type is cloneable, choose Clone and select the matching transponder ID.",
  "Put the original key in the slot, tap Start, and follow the on-screen and voice prompts. Swap in the blank when asked.",
  "Wait for the 'cloning completed' message and tap Continue.",
  "Test the clone in the car. Cloning only works for the transponder types the tool lists, and some need a different route such as IMMO programming."],
 prob:["Read fails repeatedly: change the position/direction in the slot", "Clone option not available for that ID: use the IMMO add-key route or a different tool"], warn:[LEGAL, "Cloning is for keys the customer owns. Don't clone a key you don't have authority over."]},
{tool:"Autel MaxiIM KM100X", title:"Generate a transponder (Transponder Function)", pre:["Vehicle make or transponder ID known", "Blank transponder compatible with the protocol", "Owner consent"],
 steps:[
  "Open Transponder Function, then Transponder Generation.",
  "Choose the vehicle with Vehicle Search, or use Transponder Search if you know the transponder ID and let it list matching makes.",
  "Check you picked the right make. The manual stresses this before generating.",
  "Put the blank in the transponder slot and tap Generate Transponder.",
  "When it reports success, you have a working transponder chip. It still has to be learned by the car (IMMO) unless the vehicle path says otherwise."],
 prob:["Generation fails: wrong chip type or position - re-seat or try another blank", "No matching make found: not supported for that ID"], warn:[LEGAL]},
{tool:"Autel MaxiIM KM100X", title:"Simulated key / transponder simulation (emergency start)", pre:["Vehicle that you own or have authority over", "Know the transponder ID and the register data needed (usually read from a working key)", "Tool charged and ready to be held next to the ignition area"],
 steps:[
  "Open Transponder Function -> Transponder Simulation.",
  "Pick the transponder ID. The manual lists six: ID46, ID47, ID48, ID49, ID4A, ID8A (or use the search box).",
  "Enter the parameters for each register page (P0, P1, ...) as required, then tap Simulate.",
  "When it reports success, hold the low-frequency detection collector (top antenna) within about 5 cm of the ignition / emergency-start coil area and adjust until the car detects it.",
  "Do not leave the screen - tapping Exit ends the simulation and it becomes invalid.",
  "Note this is a temporary stand-in key for emergency starts. It doesn't leave you with a permanent key."],
 prob:["Car doesn't react: reposition the collector, re-check the register values, re-run Simulate", "Simulation stopped: you left the screen, so run it again"], warn:[LEGAL, "Simulation is for lawful emergency starts on your own or authorised vehicles. It is not an alternative to proper key programming."]},
{tool:"Autel MaxiIM KM100X", title:"Remote programming (and frequency check)", pre:KEYPRE.slice(0,5).concat(["Remote with the right frequency and button layout"]),
 steps:[
  "If you're unsure of a remote's frequency, open Frequency Detection, hold the remote within about 10 cm of the key slot, press a button and read the frequency shown.",
  "Connect the VCI, open IMMO, and identify the vehicle.",
  "Look for a Remote System or remote control learning / adding function under the vehicle's menu.",
  "Follow the prompts - typically pressing a button on the remote at the right moment.",
  "If using an Autel universal key and the buttons are wrong, check Button Customization under Special Functions.",
  "Test every button and test lock/unlock from range."],
 prob:KEYPROB, warn:KEYWARN},
{tool:"Autel MaxiIM KM100X", title:"Read PIN / immobiliser information", pre:["Authorisation from the owner", "VCI connected and the car identified", "Function available for that car"],
 steps:[
  "Connect power and the VCI, open IMMO, and identify the car.",
  "Look for Vehicle IMMO Information (or similar). It can show the VIN, PIN and other immobiliser module fields where the car supports it.",
  "If a PIN is shown, record it for the owner and nobody else. It's their security code.",
  "Some cars won't give a PIN directly - don't try workarounds, check the coverage list and the tool's prompts instead."],
 prob:["No PIN available: unsupported or locked on that model", "Tool says data is locked: follow the prompts or refer on"], warn:[LEGAL, "Treat PINs as sensitive. Don't store them on shared lists or post them online."]},
{tool:"Autel MaxiIM KM100X", title:"Key cutting prep", pre:["Key blank with the right blade profile (keyway)", "Cutting is done separately: the KM100X is a programmer, not a cutting machine"],
 steps:[
  "Identify the blade type (profile / keyway) and match a blank to it. Compare with the original if you have one.",
  "Get the key code legitimately (from the existing key, the lock, or the owner's paperwork), or decode with a locksmith's tools.",
  "Cut the blade on a proper cutting machine or have a locksmith cut it. Deburr the blade.",
  "Test the cut key in the door and ignition before you program anything, so you're not chasing a programming problem that's really a cutting one.",
  "Then program the chip and remote using the other guides."],
 prob:["Key turns door but not ignition: cut slightly off or wafers worn - recut or try another blank", "Key is stiff: deburr, or the blank profile is wrong"], warn:[LEGAL, "Don't cut keys to vehicles or locks you have no authority for."]},

// ---- X100 Pro2
{tool:"XTool X100 Pro2", title:"Add a spare key", pre:KEYPRE.concat(["Tool paired / connected per its own quick-start"]),
 steps:["Verify authority and coverage on the X100 Pro2 for that car and function.","Connect charger and the tool to the car as per its instructions.","Select the vehicle (auto-detect VIN if offered, otherwise make/model/year).","Choose the key add / key learning function and follow the prompts.","Test every key and remote at the end."],
 prob:KEYPROB, warn:KEYWARN.concat(["I haven't listed X100 Pro2 menu names - confirm them on the tool."])},
{tool:"XTool X100 Pro2", title:"All keys lost (where supported)", pre:KEYPRE.concat(["AKL confirmed as supported for that exact car"]),
 steps:["Verify authority and coverage. If AKL isn't listed, stop.","Connect power and tool, identify the car.","Choose the all keys lost / key learning function for that make.","Follow prompts (some cars need additional immobiliser data first).","Make sure the blade is cut beforehand.","Test every key and remote."],
 prob:KEYPROB, warn:KEYWARN},
{tool:"XTool X100 Pro2", title:"Transponder and remote programming", pre:KEYPRE.slice(0,5),
 steps:["Identify the correct chip and remote frequency for the car (check the coverage list, or use the tool's key detection if it has one).","Connect power and the tool, identify the car.","Program the transponder with the key learning function.","Program the remote separately using the remote function.","Test starting and every remote button."],
 prob:KEYPROB, warn:KEYWARN},
{tool:"XTool X100 Pro2", title:"Read PIN / immobiliser data (where supported)", pre:["Owner authority","Function supported for that car"],
 steps:["Connect power and tool, identify the car.","Look for a PIN / security code read or immobiliser information function.","Record the PIN for the owner only.","If not offered, the car isn't supported for that function on your tool."],
 prob:["No PIN available: unsupported on that car or version"], warn:[LEGAL, "Treat PINs as sensitive."]},
{tool:"XTool X100 Pro2", title:"Key cutting prep", pre:["Correct blank and blade profile","Cutting done on a separate cutting machine or by a locksmith"],
 steps:["Match the blade profile to the original.","Cut and deburr on a proper machine (or hand over to a locksmith).","Test in the door and ignition before programming.","Then program the chip and remote."],
 prob:["Stiff or binding key: deburr, or the blank profile is wrong"], warn:[LEGAL]},

// ---- D8S
{tool:"XTool D8S", title:"Full-system fault scan", pre:["Tool charged and updated","Interface connected to OBD port","Battery healthy (or charger connected for long sessions)"],
 steps:["Connect the tool/interface to the OBD port and turn the ignition on (engine off unless the tool says otherwise).","Let the tool identify the vehicle (auto VIN) or select the make/model/year manually.","Choose the full system / all-systems scan.","Wait for the scan to complete - it can take several minutes on bigger cars.","Review the fault list by system. Save or export the report before clearing anything.","Note codes that are active vs history/pending."],
 prob:["Some modules don't respond: check the car selection and ignition state","Scan stalls: check the connection and try again","Odd lots of communication faults: low battery voltage - connect a charger"], warn:["Save the report before clearing codes.","Don't clear codes on a pre-purchase scan - show the buyer what's there."]},
{tool:"XTool D8S", title:"Clear codes", pre:["Fault scan saved first","You understand why the faults are there"],
 steps:["Run the scan and save the report.","Fix or diagnose the cause first where you can.","Choose the clear codes / erase function for the system or all systems.","Re-scan to see if any codes come back.","Drive or run the car as needed to confirm."],
 prob:["Codes return: the fault is still present","Some codes can't be cleared: fix the cause or follow the manufacturer's procedure"], warn:["Clearing codes can reset monitors, which affects readiness for a WoF-style check.","Don't clear codes to hide faults from a buyer."]},
{tool:"XTool D8S", title:"Live data", pre:["Car identified and connected","Know which parameters you're interested in"],
 steps:["Open the system you want (engine, ABS, etc.) and choose live data / data stream.","Pick the specific parameters. Fewer parameters refresh faster.","Run the engine or test as needed.","Watch values change, compare to expectations or a known-good car.","Use graph or record if the tool offers it, and save the log."],
 prob:["Data refreshes slowly: select fewer items","Parameter missing: not provided by that ECU/version"], warn:["Don't drive and watch the screen at the same time - get a passenger or park."]},
{tool:"XTool D8S", title:"Bi-directional (actuator) tests", pre:["Car safe and secure","Function listed for that car","Battery healthy or charger connected"],
 steps:["Open the system you want to test (e.g. engine, body, ABS).","Choose the active test / actuator test (names vary).","Select the component (e.g. fan, relay, injector, solenoid).","Read the on-screen warning and make sure the car is in the right state.","Start the test and listen/look/feel for the response.","Stop the test and re-scan afterwards."],
 prob:["Test not available: unsupported for that car","No response: wiring/part failure or conditions not met"], warn:["Only run tests with the car safe: handbrake on, wheels clear, nobody near moving parts.","Follow the prompts - some tests can move things or run components at full output."]},
{tool:"XTool D8S", title:"Oil service reset", pre:["Service actually done (oil and filter changed)","Car identified, ignition on"],
 steps:["Do the service first.","Open the Service / Maintenance functions and choose oil reset (names vary).","Select the car if asked.","Follow the on-screen instructions (e.g. ignition on, engine off).","Confirm the service light has reset."],
 prob:["Light stays on: different reset sequence required or a different counter - check prompts"], warn:["Only reset after the service has been done. Don't hide an overdue service."]},
{tool:"XTool D8S", title:"EPB (electric park brake) service", pre:["Know the procedure for that car (some require specific prep)","Battery charger on the car","Wheel chocks and a safe, level work area"],
 steps:["Open the EPB / brake service function and choose Retract (or service mode) - the actual label varies.","Read and follow the on-screen instructions.","Replace the rear pads.","Use the tool to re-apply / calibrate the brake after the job.","Test the park brake works and the warning light is clear."],
 prob:["Function refused: conditions not met (e.g. ignition state, door open, battery low)","Warning remains: re-run the calibration"], warn:["Don't force back the caliper piston without putting the brake into service mode on cars that need it - it can damage the motor/gear.","Check the brakes work before returning the car to the owner."]},
{tool:"XTool D8S", title:"Steering angle sensor (SAS) reset / calibration", pre:["Wheels straight ahead on a level surface","Alignment or suspension work done if relevant"],
 steps:["Centre the steering wheel and make sure the wheels are straight.","Open the SAS / steering angle reset function.","Follow the prompts - some cars want the wheel turned lock to lock.","Confirm completion and clear any related ABS/ESP faults.","Test drive in a straight line and check for warning lights."],
 prob:["ESP light stays on: wheels not straight during calibration or another fault present"], warn:["Do this after alignment or suspension work."]},
{tool:"XTool D8S", title:"Battery registration / reset", pre:["New battery fitted","Know the new battery's rating and type if the tool asks"],
 steps:["Fit the new battery.","Open the battery registration / BMS reset function.","Enter details if asked (type and capacity) - use the figures on the actual battery.","Follow the prompts to complete registration.","Check for any charging warnings."],
 prob:["Tool refuses: car not supported or conditions not met"], warn:["Registration is only needed on cars with battery management.","Don't invent battery specs - read them off the battery."]},
{tool:"XTool D8S", title:"Throttle relearn", pre:["Throttle body cleaned or replaced","Engine warm if the procedure wants it"],
 steps:["Open the throttle / throttle body adaption function.","Follow the prompts (ignition on, engine off or idle, wait times).","Don't touch the pedal unless told to.","Complete the procedure and clear related faults.","Test idle and response."],
 prob:["Rough idle persists: vacuum leak or another fault"], warn:["Follow the specific procedure for the car; don't apply the same steps to every car."]},
{tool:"XTool D8S", title:"Injector coding", pre:["New injector codes recorded from the injectors themselves","Correct car selection"],
 steps:["Read the code from each injector (on the injector, per the maker).","Open injector coding / IQA etc. (name varies).","Enter the codes against the right cylinders.","Write them and confirm.","Run the engine and check for faults."],
 prob:["Rough running or fault codes: a code was entered against the wrong cylinder"], warn:["Double-check every character - a wrong code can cause poor running."]},
{tool:"XTool D8S", title:"ABS bleed", pre:["Brake fluid correct type","Bleed procedure available for that car","Battery charger connected"],
 steps:["Do the basic bleeding at the wheels first if the service manual says so.","Open the ABS bleed / brake bleed function.","Follow the prompts to run the pump/valves while bleeding each wheel in order.","Keep the reservoir topped up and don't let it run dry.","Finish with a pedal test and fault scan."],
 prob:["Spongy pedal: air still in the system or the wrong sequence","Function not available: unsupported car"], warn:["Brake fluid damages paint.","Always test the brakes before releasing the car."]},
{tool:"XTool D8S", title:"DPF regeneration", pre:["Car in the right state (fuel level, engine warm, no major faults)","Well-ventilated area (outside)","Charger connected"],
 steps:["Scan for faults first and fix any related ones (sensors, EGR, etc).","Open the DPF regeneration function.","Read the prompts - there are conditions like coolant temp and fuel level.","Start the regen and follow instructions.","Keep the exhaust clear of anything flammable.","Re-scan and check soot values if shown."],
 prob:["Regen doesn't start: conditions not met","Regen won't complete: DPF may be blocked or another fault"], warn:["Exhaust gets very hot. Don't do this in an enclosed space.","Don't start with a flashing/serious warning present without checking why."]},
{tool:"XTool D8S", title:"Pre-purchase scan and report", pre:["Seller's consent to plug in","Tool updated","Report template/branding ready if you use one"],
 steps:["Get the seller's OK before connecting.","Do a full-system scan and save the report. Don't clear codes.","Note active vs history faults and anything that looks hidden or recently cleared.","Check live data basics (temps, fuel trims) if relevant.","Compare VIN to the paperwork.","Give the buyer the report with the date, the car details and what you did and didn't check."],
 prob:["Modules not responding: note it as 'not scanned'"], warn:["A scan isn't a mechanical inspection - say so on the report.","Don't make claims about condition you can't back up."]},

// ---- OpenPort
{tool:"Tactrix OpenPort 2.0", title:"Connect to the car", pre:PREF.concat(["OpenPort drivers and software (EcuFlash / RomRaider) installed from official sources"]),
 steps:["Install the OpenPort drivers and software first, following the Tactrix instructions.","Plug the OpenPort into the laptop, then into the OBD port.","Turn the ignition on (engine off), with accessories off.","Open EcuFlash or RomRaider and select the OpenPort as the interface if asked.","Check you can identify the ECU (ROM ID) before doing anything else."],
 prob:["Device not seen: reinstall driver, try another USB port/cable","Can't identify ECU: ignition state, wrong cable, or unsupported ECU"], warn:["Use a stable laptop power source.","Don't proceed unless the ECU ID is read correctly."]},
{tool:"Tactrix OpenPort 2.0", title:"Read and back up the stock ROM", pre:PREF,
 steps:["Connect as per the connect guide.","In EcuFlash, choose the read-from-ECU function (names can vary).","Save the file with a clear name (car, date, ROM ID).","Verify the file size looks right for that ECU.","Copy it to a second storage (USB/cloud).","Keep it untouched as your stock ROM."],
 prob:["Read fails: check connection, power and ignition state"], warn:["Do not skip this step.","Never overwrite your stock file."]},
{tool:"Tactrix OpenPort 2.0", title:"Flash with EcuFlash", pre:PREF.concat(["Stock ROM backed up","A ROM file that matches the ECU ID","Know the recovery path if the flash fails"]),
 steps:["Confirm the stock ROM is saved.","Open the new ROM in EcuFlash and check it matches the ECU.","Turn the ignition on, engine off, everything electrical off.","Choose the write/flash function and confirm.","Do not touch the cable, laptop or car during the flash.","When complete, cycle the ignition as prompted and check for faults.","Start the car and verify idle."],
 prob:["Flash fails partway: do NOT power down; try again as the software suggests","Car won't start afterwards: restore the stock ROM"], warn:["Don't interrupt a flash.","Subaru and Mitsubishi only here - check the supported ECU list for your car."]},
{tool:"Tactrix OpenPort 2.0", title:"Datalog with RomRaider", pre:["RomRaider installed with the right ECU definitions","OpenPort connected"],
 steps:["Open RomRaider Logger and select the OpenPort.","Let it identify the ECU. Make sure a definition for that ROM ID is loaded.","Choose the parameters you want to log.","Start logging, drive safely, and stop when done.","Save the log and review it (AFR, boost, knock etc.)."],
 prob:["No definition for the ROM ID: you need a matching definition file","Slow log rate: select fewer parameters"], warn:["Don't operate the laptop while driving - use a passenger."]},
{tool:"Tactrix OpenPort 2.0", title:"Restore stock ROM", pre:PREF.concat(["The saved stock ROM for that car"]),
 steps:["Open the stock ROM file you saved earlier.","Check the ROM ID matches the car's ECU.","Use the write function in EcuFlash as in the flash guide.","Cycle the ignition and clear codes if needed.","Start and check."],
 prob:["Mismatch between ROM and ECU: stop and re-check"], warn:["Never flash a ROM you can't confirm matches the ECU."]},

// ---- KESS V2
{tool:"KESS V2", title:"Read ECU (OBD)", pre:PREF.concat(["Genuine KESS V2 and licensed software","Vehicle/ECU confirmed on the supported list","Not a Subaru (use the OpenPort)"]),
 steps:["Connect the charger and wait for stable voltage.","Plug KESS V2 into the OBD port and the PC.","Select the vehicle and ECU in the software.","Choose OBD read and follow the on-screen steps.","Save the original file to two locations."],
 prob:["Communication failure: check connection, ignition and supported list","ECU not supported: stop"], warn:["Clones can brick ECUs.","Not for Subaru."]},
{tool:"KESS V2", title:"Back up the original file", pre:["A completed read"],
 steps:["Name the file clearly (car, ECU, date).","Check the size is sensible.","Copy to a second location.","Keep the original read-only."],
 prob:["File seems too small: re-read before doing anything else"], warn:["No original file, no write."]},
{tool:"KESS V2", title:"Write a tuned file", pre:PREF.concat(["Original saved","A tune file that matches the ECU and software version"]),
 steps:["Check the original is saved.","Load the modified file and confirm it matches.","Turn the ignition on and make sure the charger holds the voltage.","Start the write and don't interrupt it.","Cycle the ignition as prompted.","Test start, idle and check for faults."],
 prob:["Write fails: do not power off; follow the tool's recovery steps","Warning lights after: scan and consider restoring stock"], warn:["Interrupting a write can brick the ECU.","Stage 1 / economy tunes only on supported cars and legal for road use."]},
{tool:"KESS V2", title:"Restore stock file", pre:PREF.concat(["The original file you saved"]),
 steps:["Load the original file.","Confirm it matches the ECU.","Write it back as for any write.","Cycle the ignition.","Scan and test."],
 prob:["Mismatch warning: stop and re-check which file you're using"], warn:["Never overwrite your original."]},
{tool:"KESS V2", title:"TCU read/write (where supported)", pre:PREF.concat(["TCU listed as supported for the car"]),
 steps:["Check TCU is on the supported list.","Connect and select the TCU entry.","Read and back up the original.","Write only if you have a matching file.","Cycle ignition and road test carefully."],
 prob:["TCU not listed: not supported"], warn:["Gearbox control faults are safety-relevant - road test carefully."]},
{tool:"KESS V2", title:"KESS V2 safety rules", pre:["Genuine KESS V2 unit and licensed software","Battery charger available"],
 steps:["Genuine tool only.","Charger on the car every time.","Original file saved first, every time.","Check the supported list.","Never on Subaru - use the OpenPort.","Don't interrupt reads or writes."],
 prob:["ECU unresponsive after a failed write: may need bench/boot recovery - do not keep retrying blindly"], warn:["Clones can brick ECUs."]},

// ---- CANable
{tool:"CANable 2.0 Pro", title:"Set up with SavvyCAN (candleLight firmware)", pre:["CANable 2.0 Pro","SavvyCAN installed","OBD breakout / cable you trust","Know what firmware it's running"],
 steps:["Find out what firmware is on the adapter. Many are used with candleLight (gs_usb) firmware, others with slcan-style firmware - check yours.","On Linux with gs_usb firmware, the adapter appears as a SocketCAN interface (e.g. can0). Bring it up at the right bitrate with the ip link command.","In SavvyCAN, add a connection of the matching type (SocketCAN on Linux). Other platforms depend on firmware - check the SavvyCAN docs for your setup.","Pick the bitrate used by the bus you're connecting to. 500 kbit/s is common on OBD pins 6 and 14, but it varies, and other buses use other speeds.","Turn on listen-only mode if available so you don't transmit anything."],
 prob:["No interface: wrong firmware or driver","No frames: wrong bitrate or wrong pins","Errors on bus: wrong speed - stop and recheck"], warn:["Listen-only first.","Don't transmit onto a car you don't understand."]},
{tool:"CANable 2.0 Pro", title:"Log CAN traffic", pre:["Adapter connected and SavvyCAN showing frames"],
 steps:["Start with the car in a known state (ignition on, engine off, say).","Start capturing in SavvyCAN.","Do one thing at a time (lock/unlock, lights, pedal) and note the time.","Stop the capture and save the log.","Keep notes on what you did and when."],
 prob:["Huge logs: capture shorter sessions","Missing frames: bus load or wrong bitrate"], warn:["Don't operate the laptop while driving.","Gateways on newer cars may block access."]},
{tool:"CANable 2.0 Pro", title:"Find message IDs for an action", pre:["Logs captured before and during an action"],
 steps:["Capture a baseline with nothing happening.","Capture again while doing one action (e.g. headlights on).","Compare the two in SavvyCAN's tools (frame filter / diff / graphing) to see which IDs change.","Repeat the action a few times to confirm it's consistent.","Look at which bytes/bits change and record your findings."],
 prob:["Too many changing IDs: do the action in isolation, repeated"], warn:["Watch only. Don't replay messages on a live car, particularly anything touching safety systems."]},

// ---- PS100
{tool:"Autel PS100 - confirm model function", title:"Stable power / programming support (generic)", pre:["Confirm what the PS100 actually is and does (label, manual, Autel support) before relying on this"],
 steps:["Read the manual that came with it, or confirm with Autel/your supplier.","Connect and switch on the power supply first, then check it holds steady voltage.","Connect to the vehicle / tool exactly as the manual says.","Start the programming job and keep everything connected.","Wait for the job to finish before disconnecting.","Disconnect in the reverse order."],
 prob:["No power / unstable: check cables and source","Tool doesn't recognise it: the model function may be different from what you expect"], warn:["Keep voltage stable during programming.","Don't list it as a service until its function is confirmed.","These are generic steps only."]}
];
